# Generated by Django 4.1.5 on 2023-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('Views', models.CharField(max_length=200, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
