# Generated by Django 4.1.5 on 2023-01-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('job_type', models.CharField(max_length=200, null=True)),
                ('job_profile', models.CharField(choices=[('Summer Internship', 'Summer Internship'), ('Winter Internship and Job', 'Winter Internship and Job'), ('Job only', 'Job only'), ('Winter Internship only', 'Winter Internship only')], max_length=200, null=True)),
            ],
        ),
    ]
