# Generated by Django 4.1.5 on 2023-01-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.customer'),
        ),
    ]
