# Generated by Django 4.1.5 on 2023-01-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_new_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='college',
            new_name='job_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='job_profile',
            field=models.CharField(choices=[('Summer Internship', 'Summer Internship'), ('Winter Internship and Job', 'Winter Internship and Job'), ('Job only', 'Job only'), ('Winter Internship only', 'Winter Internship only')], max_length=200, null=True),
        ),
    ]
