# Generated by Django 4.1.5 on 2023-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_rename_college_customer_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('Area', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=20000, null=True)),
                ('rating', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobProfile', models.CharField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.CharField(choices=[('Summer Internship', 'Summer Internship'), ('Winter Internship and Job', 'Winter Internship and Job'), ('Job only', 'Job only')], max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='job_type',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='job_profile',
        ),
    ]
