# Generated by Django 4.1.5 on 2023-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_customer_comp_experience_job_profile_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('Views', models.CharField(max_length=200, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
