# Generated by Django 4.1.5 on 2023-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_main_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('jobTypes', models.CharField(choices=[('Summer Internship', 'Summer Internship'), ('Winter Internship and Job', 'Winter Internship and Job'), ('Job only', 'Job only')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('jobProfiles', models.CharField(max_length=20000, null=True)),
                ('Views', models.CharField(max_length=200, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
